export const typeColorTags = {
  documento: {
    title: 'documento',
    color: 'bg-yellow-500',
  },
  metadatos: {
    title: 'metadatos',
    color: 'bg-red-500',
  },
  agrupación: {
    title: 'agrupación',
    color: 'bg-purple-500',
  },
  textual: {
    type: 'textual',
    color: 'bg-green-500',
  },
  multimedia: {
    type: 'multimedia',
    color: 'bg-cyan-500',
  },
  tablas: {
    type: 'tablas',
    color: 'bg-orange-500',
  },
  formulario: {
    type: 'formulario',
    color: 'bg-slate-500',
  },
  scripting: {
    type: 'scripting',
    color: 'bg-amber-500',
  },
  interactivas: {
    type: 'interactivas',
    color: 'bg-amber-500',
  },
  semánticas: {
    type: 'semánticas',
    color: 'bg-indigo-500',
  },
  ideogramáticas: {
    type: 'ideogramáticas',
    color: 'bg-lime-500',
  },
  edición: {
    type: 'edición',
    color: 'bg-pink-500',
  },
}

export const tags = [
  /* {
    id: 1,
    title: 'html',
    type: typeColorTags.documento.title,
    color: typeColorTags.documento.color,
    information: [
      {
        code: {
          titleTag: 'html',
          bodyTag: '',
          description: '',
        },
        images: [
          {
            src: '/img.png',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: 'head',
    type: typeColorTags.documento.title,
    color: typeColorTags.documento.color,
  },
  {
    id: 3,
    title: 'body',
    type: typeColorTags.documento.title,
    color: typeColorTags.documento.color,
  }, */
  {
    id: 4,
    title: 'title',
    type: typeColorTags.metadatos.title,
    color: typeColorTags.metadatos.color,
    information: [
      {
        code: {
          bodyTag: `<head>\n<title>HTML TAGS</title>\n</head>`,
          description: '',
        },
        images: [
          {
            src: '/img.png',
          },
        ],
      },
    ],
  },
  {
    id: 5,
    title: 'base',
    type: typeColorTags.metadatos.title,
    color: typeColorTags.metadatos.color,
  },
  {
    id: 6,
    title: 'link',
    type: typeColorTags.metadatos.title,
    color: typeColorTags.metadatos.color,
  },
  {
    id: 7,
    title: 'meta',
    type: typeColorTags.metadatos.title,
    color: typeColorTags.metadatos.color,
  },
  {
    id: 8,
    title: 'style',
    type: typeColorTags.metadatos.title,
    color: typeColorTags.metadatos.color,
  },
  {
    id: 9,
    title: 'p',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 10,
    title: 'hr',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 11,
    title: 'pre',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 12,
    title: 'blockquote',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 13,
    title: 'ol',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 14,
    title: 'ul',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 15,
    title: 'li',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 16,
    title: 'dl',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 17,
    title: 'dt',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 18,
    title: 'dd',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 19,
    title: 'figure',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 20,
    title: 'figcaption',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 21,
    title: 'div',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 22,
    title: 'main',
    type: typeColorTags.agrupación.title,
    color: typeColorTags.agrupación.color,
  },
  {
    id: 23,
    title: 'a',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 24,
    title: 'em',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 25,
    title: 'strong',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 26,
    title: 'small',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 27,
    title: 's',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 28,
    title: 'cite',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 29,
    title: 'q',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 30,
    title: 'dfn',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 31,
    title: 'abbr',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 32,
    title: 'data',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 33,
    title: 'time',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 34,
    title: 'code',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 35,
    title: 'var',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 36,
    title: 'samp',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 37,
    title: 'kbd',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 38,
    title: 'sub',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 39,
    title: 'i',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 40,
    title: 'b',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 41,
    title: 'u',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 42,
    title: 'mark',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 43,
    title: 'span',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 44,
    title: 'br',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 45,
    title: 'wbr',
    type: typeColorTags.textual.title,
    color: typeColorTags.textual.color,
  },
  {
    id: 46,
    title: 'img',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 47,
    title: 'picture',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 48,
    title: 'iframe',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 49,
    title: 'embed',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 50,
    title: 'object',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 51,
    title: 'param',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 52,
    title: 'video',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 53,
    title: 'audio',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 54,
    title: 'source',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 55,
    title: 'track',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 56,
    title: 'map',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 57,
    title: 'area',
    type: typeColorTags.multimedia.title,
    color: typeColorTags.multimedia.color,
  },
  {
    id: 58,
    title: 'table',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 59,
    title: 'caption',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 60,
    title: 'colgroup',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 61,
    title: 'col',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 62,
    title: 'tbody',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 63,
    title: 'thead',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 64,
    title: 'tfoot',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 65,
    title: 'tr',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 66,
    title: 'th',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 67,
    title: 'td',
    type: typeColorTags.tablas.title,
    color: typeColorTags.tablas.color,
  },
  {
    id: 68,
    title: 'form',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 69,
    title: 'label',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 70,
    title: 'input',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 71,
    title: 'button',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 72,
    title: 'select',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 73,
    title: 'datalist',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 74,
    title: 'optgroup',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 75,
    title: 'option',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 76,
    title: 'textarea',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 77,
    title: 'output',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 78,
    title: 'progress',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 79,
    title: 'meter',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 80,
    title: 'fieldset',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 81,
    title: 'legend',
    type: typeColorTags.formulario.title,
    color: typeColorTags.formulario.color,
  },
  {
    id: 82,
    title: 'script',
    type: typeColorTags.scripting.title,
    color: typeColorTags.scripting.color,
  },
  {
    id: 83,
    title: 'noscript',
    type: typeColorTags.scripting.title,
    color: typeColorTags.scripting.color,
  },
  {
    id: 84,
    title: 'template',
    type: typeColorTags.scripting.title,
    color: typeColorTags.scripting.color,
  },
  {
    id: 85,
    title: 'slot',
    type: typeColorTags.scripting.title,
    color: typeColorTags.scripting.color,
  },
  {
    id: 86,
    title: 'canvas',
    type: typeColorTags.scripting.title,
    color: typeColorTags.scripting.color,
  },
  {
    id: 87,
    title: 'details',
    type: typeColorTags.interactivas.title,
    color: typeColorTags.interactivas.color,
  },
  {
    id: 88,
    title: 'summary',
    type: typeColorTags.interactivas.title,
    color: typeColorTags.interactivas.color,
  },
  {
    id: 89,
    title: 'dialog',
    type: typeColorTags.interactivas.title,
    color: typeColorTags.interactivas.color,
  },
  {
    id: 90,
    title: 'article',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 91,
    title: 'section',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 92,
    title: 'nav',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 93,
    title: 'hgroup',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 94,
    title: 'h1',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 95,
    title: 'h2',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 96,
    title: 'h3',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 97,
    title: 'h4',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 98,
    title: 'h5',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 99,
    title: 'h6',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 100,
    title: 'search',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 101,
    title: 'header',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 102,
    title: 'footer',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 103,
    title: 'aside',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 104,
    title: 'address',
    type: typeColorTags.semánticas.title,
    color: typeColorTags.semánticas.color,
  },
  {
    id: 105,
    title: 'ruby',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 106,
    title: 'rb',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 107,
    title: 'rt',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 108,
    title: 'rtc',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 109,
    title: 'rp',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 110,
    title: 'bdi',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 111,
    title: 'bdo',
    type: typeColorTags.ideogramáticas.title,
    color: typeColorTags.ideogramáticas.color,
  },
  {
    id: 112,
    title: 'ins',
    type: typeColorTags.edición.title,
    color: typeColorTags.edición.color,
  },
  {
    id: 113,
    title: 'del',
    type: typeColorTags.edición.title,
    color: typeColorTags.edición.color,
  },
]
